/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.obscure.ticarousel;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;

@Kroll.module(name = "Android", id = "com.obscure.ticarousel")
public class AndroidModule extends KrollModule {

	private static final String		LCAT	= "AndroidModule";

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
	}

}
